
POST https://api.jinwoo.space/api/members
Content-Type: application/json

{
  "email": "jwjung5038@gmail.com",
  "username": "정진우",
  "password": "passw0rd"
}
###
OPTIONS http://localhost:8080/auth
Content-Type: application/json

{
"email": "jwjung5038@gmail.com",
"password": "passw0rd"
}

> {% client.global.set("auth_token", response.body.token); %}

### public
GET http://localhost:8080/api/webtoons?day-of-week=MONDAY


### public
GET http://localhost:8080/api/webtoons

### public
POST http://localhost:8080/api/members/certification/send
Content-Type: application/json

{
  "phoneNumber": "+82-1072421962"
}

### auth required
GET http://localhost:8080/api/alarms
Authorization: Bearer {{auth_token}}